version: '3'

services:
  backend_tfg:
    image: josecarlospg2907/backend
    ports:
      - "8081:80"
      - "8082:3306"
      - "8083:8000"
    networks:
      red_tfg_pgp:
        ipv4_address: 172.20.0.2
    container_name: backend_tfg

  frontend_tfg:
    image: josecarlospg2907/frontend
    ports:
      - "8084:4200"
    networks:
      red_tfg_pgp:
        ipv4_address: 172.20.0.3
    container_name: frontend_tfg
    depends_on:
      - backend_tfg


networks:
  red_tfg_pgp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
